### ISSUE TITLE
bug: Kubernetes no longer supports Dockershim 1.24

### ISSUE THREAD

**Issue by dberuben** [lacework/terraform-kubernetes-agent#54]
**Describe the bug**

the Kubernetes team plans to completely remove the runtime in Kubernetes version 1.24. Amazon EKS will be ending support for Dockershim starting with the Kubernetes version 1.24 launch. Amazon EKS AMIs that are officially published will have containerd as the only runtime starting with version 1.24.

Look like lacework (lacework/datacollector) is still mounting a docker socket as a daemonset  

```
NAMESPACE	TYPE		NAME		STATUS
kube-system	daemonset	lacework-agent	mounted
```

Are you planning to support containerd? 

Source https://docs.aws.amazon.com/eks/latest/userguide/dockershim-deprecation.html

**Comment by afiune** [comment]
Hi @dberuben - Thank you for your feedback. We already support containerd: https://docs.lacework.com/supported-operating-systems#container-runtime

We think the confusion might be that in our daemonset deployment we unconditionally try to do a volume mount of the docker socket, regardless of whether docker is actually used.  **If containerd is in use, this is a no-op**, datacollector finds the containerd socket another way.

https://github.com/lacework/terraform-kubernetes-agent/blob/main/main.tf#L113-L116
```hcl
          volume_mount {
            name       = "run-sock"
            mount_path = "/var/run/docker.sock"
          }
```

Ideally, we should remove this since it doesn’t make sense in the containerd world, but since we just have one Terraform module it still needs this for legacy support.

**Comment by dberuben** [comment]
@afiune Thank you for the update
